### ISSUE TITLE
Enhancement for adding new entities

### ISSUE THREAD

**Issue by anym001** [martinarva/dynamic_energy_cost#1]
At the moment, the entities have to be copied manually into the configuration window. 

Is it possible for a selection list to be displayed during configuration in which only EUR/kWh sensors are displayed for the electricity price and only W sensors for the power usage?

This ensures that the correct entries are entered and is also more convenient.

Similar to the creation of "energy from real power sensor" in powercalc.
![2024-04-18_06-53](https://github.com/martinarva/dynamic_energy_cost/assets/109074292/48e3a858-6ffe-4567-b5f2-ad99aea2968f)

**Comment by martinarva** [comment]
yes, this is in to-do list

**Comment by martinarva** [comment]
Thanks to @basbruss, we have now entity selectors in config flow.
