### ISSUE TITLE
async_create_task warning in logs

### ISSUE THREAD

**Issue by dunxd** [martinarva/dynamic_energy_cost#12]
**Describe the bug**
> Detected that custom integration 'dynamic_energy_cost' calls async_create_task from a thread at custom_components/dynamic_energy_cost/energy_based_sensors.py, line 147: self.hass.async_create_task(self.async_update()), please report it to the author of the 'dynamic_energy_cost' custom integration

**Comment by martinarva** [comment]
Fixed in latest release: https://github.com/martinarva/dynamic_energy_cost/releases/tag/v0.2.5

Please verify and close

**Comment by dunxd** [comment]
Warning gone after update. 😁
