### ISSUE TITLE
Weekly costs

### ISSUE THREAD

**Issue by jluyten** [martinarva/dynamic_energy_cost#21]
Hi

I love the fact that you made this on a daily, monthly and yearly basis!

Is it possible to also add a weekly number?

Cheers!

Jannik

**Comment by martinarva** [comment]
I think best would be to make the periods configurable, when you first configure the integration, as there is also a request for all time cost. For now, I don't have an idea how to do this, but will look into it. 

Meanwhile I recommend to use HA-s built in Utility Meter. Feed in any of the cost entities and choose reset period of one week.

**Comment by martinarva** [comment]
Done by @JannikL87 in pull request https://github.com/martinarva/dynamic_energy_cost/pull/34 and will be included in the next release.
