### ISSUE TITLE
Use currency from the price sensor for power based sensors

### ISSUE THREAD

**Issue by kbhsn4** [martinarva/dynamic_energy_cost#35]
Currently the energy based sensor function extract the currency from the price function, and uses that as the unit_of_measurement (and defaults to EUR in case of a lack of currency). Which is great!

Please extent this functionality to the power based sensor function, which always uses EUR regardless of which currency is used in the price sensor.

**Comment by martinarva** [comment]
Added in the commit https://github.com/martinarva/dynamic_energy_cost/commit/6ea0287f906d49df1fb7f8643e34c816b44cf72c

Will be available in version 0.5.0

**Comment by martinarva** [comment]
Version 0.5.0 released: https://github.com/martinarva/dynamic_energy_cost/releases/tag/v0.5.0
