### ISSUE TITLE
Energy Sensor wrong decimals?

### ISSUE THREAD

**Issue by GregorEstebanCardosoSchiller** [martinarva/dynamic_energy_cost#36]
Hi, see here the "feeding sensors" and the values from your integration. Electricity price is a dynamic price from tibber, I want to accumulate the value of my self-used energy production.

![image](https://github.com/martinarva/dynamic_energy_cost/assets/65222903/1e96dac6-e091-4667-92d2-2a1fada6bb4e)

As you can see I have a real time (unit W) and a riemann sum sensor (unit Wh). I seems that the sum cost is off a kilo.

**Comment by martinarva** [comment]
Hi!

You should feed in the energy sensor, but it has to be in kwh not wh. Make a template sensor from the Wh, divide it by 1000 and feed in this template sensor to the integration.
