### ISSUE TITLE
Describe update process in readme

### ISSUE THREAD

**Issue by anym001** [martinarva/dynamic_energy_cost#5]
How does an update work with this plugin? Does the complete dynamic_energy_cost folder have to be replaced or only the changed files?

It would be great if this were described in the readme.

**Comment by martinarva** [comment]
The whole directory because there are now two different methods - energy_based_sensors and power_based_sensors and sensors.py is calling them out. Also config_flow.py is modified and translations/en.json

**Comment by anym001** [comment]
Okay, interesting. I deleted the whole folder, copied the new folder from the zip file into it and restarted. My configured sensors were then gone. 

Where are these saved? Normally outside the custom_components folder, right?

**Comment by martinarva** [comment]
> Okay, interesting. I deleted the whole folder, copied the new folder from the zip file into it and restarted. My configured sensors were then gone.
> 
> Where are these saved? Normally outside the custom_components folder, right?

Did you donloaded the latest release or latest code from main? There were some mistakes in v0.2.0, i made the new release v0.2.1 which has the latest fixes. Sorry, i'm a bit n00b in this field :)

But the senors should surviuve the update. If not, configure the integration again, it should bisck up the created sensors and last state fo them is you put in the same energy or power sensor.

**Comment by martinarva** [comment]
Updating information added to readme:

## Updating

To update the integration to a newer version:

1. Access the GitHub repository for this integration.
2. Download the latest ZIP file of the repository and extract its contents.
3. Overwrite the `dynamic_energy_cost` folder into the `custom_components` directory located typically at `/config/custom_components/` in your Home Assistant directory.

**Comment by anym001** [comment]
> Did you donloaded the latest release or latest code from main? There were some mistakes in v0.2.0, i made the new release v0.2.1 which has the latest fixes. Sorry, i'm a bit n00b in this field :)

I downloaded the latest release, maybe it was because of that. 

No problem, as you know, you grow with your tasks and challenges. :)
