### ISSUE TITLE
Prepare for future 15 minute Spot prices

### ISSUE THREAD

**Issue by jkkataja** [martinarva/dynamic_energy_cost#7]
The spot price market seems to be migrating at some point to 15 minute price intervals as opposed to 60 minute intervals

While it may take some years for this change to take full effect (e.g., in Finland customer import/export balance is on 15 minute level, price is still at 60 minute for now) it may be beneficial to prepare already at this stage the code so, that it can be easily adjusted based on market rules.

There shouldn’t be too much focus at this stage on this, but rather being mindful when coding not to cause issues in the future.

**Comment by martinarva** [comment]
Actually price change frequency does not matter.

Cost calculation is made every time the energy entity changes. It then calculates the difference between new reading and last reading multiples it with energy price and adds the value to cost.

So it will check the current price on every update. Caveat is that energy sensor must update frequently. Usually it does and if it does not then it would be impossible to calculate cost anyway.

I went with this logic to mitigate the risk of losing data or doing wrong calculations when restart or what ever happens.

If the new value is lower (for example energy sensor resets) it will not do the calculation and just stores the energy value for the next energy sensor update. 

This prevents cost decrease. Kind of similar logic as total_increase in HA.

**Comment by jkkataja** [comment]
Sounds good, wanted to bring this up just in case earlier rather than later 😁

**Comment by martinarva** [comment]
15 minute Spot prices are covered in the logic
